version: '3.8'
services:
  empire-server:
    image: bcsecurity/empire:latest
    ports:
      - "1337:1337" # Empire REST API
      - "5000:5000" # Empire Socket
    volumes:
      - ~/.empire/app-data:/root/.empire/app-data # Persist Empire data and configs
    depends_on:
      - empire-db

  empire-db:
    image: mysql:5.7 # Or another database image
    environment:
      MYSQL_ROOT_PASSWORD: your_secure_password
      MYSQL_DATABASE: empire_db
    volumes:
      - db-data:/var/lib/mysql # Persist database data

volumes:
  empire-data:
  db-data: